services:
  mysql:
    image: 'mysql'
    environment:
      - 'MYSQL_DATABASE=apicontructor'
      - 'MYSQL_PASSWORD=senha1234'
      - 'MYSQL_ROOT_PASSWORD=senha1234'
      - 'MYSQL_USER=mysqluser'
    ports:
      - '3400:3306'